# Generated by Django 5.2.17 on 2026-09-29 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offsetsubmission',
            name='claimant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offsetsubmission',
            name='claimant_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='offsetsubmission',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReassignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_label', models.CharField(default='', max_length=64)),
                ('tool_code', models.CharField(db_index=True, max_length=32)),
                ('from_claimant_name', models.CharField(blank=True, default='', max_length=150)),
                ('to_claimant_name', models.CharField(max_length=150)),
                ('operator_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassign_logs', to='desk.offsetsubmission')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
